version: '3.8'

services:
  server:
    build: apps/server
    ports:
      - 3000:3000
  db:
    image: postgres:16-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: research-hub
    volumes:
      - postgres_data:/var/lib/postgresql/data
  pg_admin:
    image: dpage/pgadmin4
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: db@db.com
      PGADMIN_DEFAULT_PASSWORD: admin
volumes:
  postgres_data:
